sudo: false
language: cpp
compiler: g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - g++-7
      - cmake
      - cmake-data
      - libgtest-dev
before_script:
  - cd /usr/src/gtest 
  - cmake .
  - cmake --build .
  - mv libg* /usr/local/lib
script: g++ test.cpp -std=c++14 -lgtest -lgtest_main -lpthread