sudo: false
language: cpp
compiler: g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - g++-7
      - cmake
      - cmake-data
      - libgtest-dev
script: g++ test.cpp -std=c++14 -lgtest -lgtest_main -lpthread