language: cpp
compiler: g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - g++-7
      - cmake
      - cmake-data
      - libgtest-dev
before_script:
  - cd /usr/src/gtest 
  - sudo mkdir build
  - cd build 
  - sudo cmake ..
  - make
  - sudo mv libg* /usr/local/lib
script: g++ test.cpp -std=c++11 -I$/usr/include -L$/usr/local/lib -lgtest -lgtest_main -lpthread