language: cpp
compiler: g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - g++-7
      - cmake
before_script:
 - git clone https://github.com/google/googletest.git
 - cd googletest
 - sudo mkdir build
 - cd build
 - sudo cmake ..
 - sudo make
 - cd ..
 - cd ..
 - export GTEST_ROOT=$PWD
 - export GTEST_INCLUDEDIR=$GTESTROOT/googletest/include
 - export GMOCK_INCLUDEDIR=$GTESTROOT/googlemock/include
 - export GMOCK_LIBDIR=$GTESTROOT/build/googlemock
 - export GTEST_LIBDIR=$GTESTROOT/build/googlemock/gtest
script: g++ test.cpp -std=c++11 -I$GTEST_INCLUDEDIR -L$GTEST_LIBDIR -lgtest -lgtest_main -lpthread